version: '3'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    command: carton exec -- perl -Ilib script/example-server --host 0.0.0.0
    volumes:
      - .:/app
    stdin_open: true
    tty: true