version: '3'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    command: carton exec -- plackup -L Shotgun script/example-server
    volumes:
      - .:/app
    stdin_open: true
    tty: true